/** Mock Telemetry data aligned with AgentPulse schema for standalone demo and offline resilience. */

import type {
  Agent as ApiAgent,
  AlertItem,
  SpanDetail,
  TraceListItem,
  PlatformHealth,
  Metrics,
  ApiKeySummary,
} from './api';
import type { DriftEntry } from './adapters';

export const MOCK_AGENTS: ApiAgent[] = [
  {
    agent_id: 'research-orchestrator',
    agent_role: 'Multi-Agent Pipeline Coordinator',
    pipeline_id: 'pipe-deep-research',
    first_seen: '2026-09-18T08:00:00Z',
    last_seen: '2026-09-18T13:20:00Z',
    total_spans: 482,
    total_errors: 2,
    error_rate: 0.004,
    avg_latency_ms: 184.2,
    avg_risk_score: 0.08,
    current_asi: 96.4,
  },
  {
    agent_id: 'retrieval-specialist',
    agent_role: 'Vector DB & Hybrid Document Retrieval',
    pipeline_id: 'pipe-deep-research',
    first_seen: '2026-09-18T08:00:00Z',
    last_seen: '2026-09-18T13:22:00Z',
    total_spans: 389,
    total_errors: 1,
    error_rate: 0.003,
    avg_latency_ms: 94.8,
    avg_risk_score: 0.12,
    current_asi: 93.1,
  },
  {
    agent_id: 'tool-execution-agent',
    agent_role: 'Sandbox Code Runner & API Integrations',
    pipeline_id: 'pipe-deep-research',
    first_seen: '2026-09-18T08:00:00Z',
    last_seen: '2026-09-18T13:24:00Z',
    total_spans: 312,
    total_errors: 5,
    error_rate: 0.016,
    avg_latency_ms: 312.6,
    avg_risk_score: 0.22,
    current_asi: 88.5,
  },
  {
    agent_id: 'grounding-evaluator',
    agent_role: 'Real-time NLI Entailment & Claim Extraction',
    pipeline_id: 'pipe-deep-research',
    first_seen: '2026-09-18T08:00:00Z',
    last_seen: '2026-09-18T13:25:00Z',
    total_spans: 240,
    total_errors: 0,
    error_rate: 0.0,
    avg_latency_ms: 118.5,
    avg_risk_score: 0.04,
    current_asi: 98.7,
  },
  {
    agent_id: 'synthesis-formulator',
    agent_role: 'Final Response Reasoning & Formulation',
    pipeline_id: 'pipe-deep-research',
    first_seen: '2026-09-18T08:00:00Z',
    last_seen: '2026-09-18T13:26:00Z',
    total_spans: 195,
    total_errors: 2,
    error_rate: 0.01,
    avg_latency_ms: 142.1,
    avg_risk_score: 0.15,
    current_asi: 94.2,
  },
];

export const MOCK_DRIFT: DriftEntry[] = [
  {
    agent_id: 'research-orchestrator',
    current_asi: 96.4,
    latest_centroid_distance: 0.082,
    latest_window_centroid_distance: 0.075,
    latest_tool_drift: 0.021,
    baseline_size: 120,
  },
  {
    agent_id: 'retrieval-specialist',
    current_asi: 93.1,
    latest_centroid_distance: 0.145,
    latest_window_centroid_distance: 0.138,
    latest_tool_drift: 0.042,
    baseline_size: 100,
  },
  {
    agent_id: 'tool-execution-agent',
    current_asi: 88.5,
    latest_centroid_distance: 0.285,
    latest_window_centroid_distance: 0.292,
    latest_tool_drift: 0.185,
    baseline_size: 80,
  },
  {
    agent_id: 'grounding-evaluator',
    current_asi: 98.7,
    latest_centroid_distance: 0.042,
    latest_window_centroid_distance: 0.038,
    latest_tool_drift: 0.011,
    baseline_size: 60,
  },
  {
    agent_id: 'synthesis-formulator',
    current_asi: 94.2,
    latest_centroid_distance: 0.165,
    latest_window_centroid_distance: 0.152,
    latest_tool_drift: 0.063,
    baseline_size: 75,
  },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: 101,
    alert_type: 'TOOL_CLAIM_OVERCLAIM',
    severity: 'critical',
    message: 'Agent asserted file batch processing completed for 50 records, but tool output indicated execution stopped at record 12.',
    agent_id: 'tool-execution-agent',
    trace_id: 'tr-8942a1',
    span_id: 'sp-tool-8942-03',
    acknowledged: false,
    resolved: false,
    created_at: '2026-09-18T12:45:00Z',
    details: { claimed_count: 50, verified_count: 12, error_cause: 'rate_limit_exceeded' },
  },
  {
    id: 102,
    alert_type: 'GROUNDING_CONTRADICTION',
    severity: 'warning',
    message: 'Synthesis claimed 300,000 patients in trial contrary to retrieved document stating 45 murine models.',
    agent_id: 'synthesis-formulator',
    trace_id: 'tr-7721b4',
    span_id: 'sp-synth-7721-02',
    acknowledged: true,
    resolved: false,
    created_at: '2026-09-18T11:15:00Z',
    details: { contradiction_confidence: 0.942, claim_span: '300,000 patients' },
  },
  {
    id: 103,
    alert_type: 'DRIFT_SPIKE',
    severity: 'warning',
    message: 'Tool execution centroid distance (0.292) approaching critical drift threshold (0.300).',
    agent_id: 'tool-execution-agent',
    trace_id: 'tr-8942a1',
    span_id: null,
    acknowledged: false,
    resolved: false,
    created_at: '2026-09-18T10:30:00Z',
    details: { centroid_distance: 0.292, threshold: 0.3 },
  },
];

export const MOCK_TRACES: TraceListItem[] = [
  {
    trace_id: 'tr-8942a1',
    pipeline_id: 'pipe-deep-research',
    start_time: '2026-09-18T13:10:00Z',
    end_time: '2026-09-18T13:10:01.450Z',
    status: 'error',
    total_spans: 4,
    overall_risk_score: 0.78,
    service_name: 'research-orchestrator',
  },
  {
    trace_id: 'tr-7721b4',
    pipeline_id: 'pipe-deep-research',
    start_time: '2026-09-18T13:05:00Z',
    end_time: '2026-09-18T13:05:01.120Z',
    status: 'completed',
    total_spans: 5,
    overall_risk_score: 0.62,
    service_name: 'research-orchestrator',
  },
  {
    trace_id: 'tr-6512c9',
    pipeline_id: 'pipe-deep-research',
    start_time: '2026-09-18T12:58:00Z',
    end_time: '2026-09-18T12:58:00.890Z',
    status: 'completed',
    total_spans: 4,
    overall_risk_score: 0.05,
    service_name: 'research-orchestrator',
  },
  {
    trace_id: 'tr-5431d2',
    pipeline_id: 'pipe-deep-research',
    start_time: '2026-09-18T12:42:00Z',
    end_time: '2026-09-18T12:42:01.210Z',
    status: 'completed',
    total_spans: 5,
    overall_risk_score: 0.03,
    service_name: 'research-orchestrator',
  },
  {
    trace_id: 'tr-4320e8',
    pipeline_id: 'pipe-deep-research',
    start_time: '2026-09-18T12:30:00Z',
    end_time: '2026-09-18T12:30:00.740Z',
    status: 'completed',
    total_spans: 3,
    overall_risk_score: 0.02,
    service_name: 'research-orchestrator',
  },
];

export const MOCK_SPANS_BY_TRACE: Record<string, SpanDetail[]> = {
  'tr-8942a1': [
    {
      span_id: 'sp-orch-8942-01',
      parent_span_id: null,
      agent_id: 'research-orchestrator',
      agent_role: 'Multi-Agent Pipeline Coordinator',
      event_type: 'workflow_start',
      span_kind: 'orchestration',
      latency_ms: 1450,
      status: 'error',
      error_message: 'Tool execution claim validation failed',
      model: 'gemini-2.5-flash',
      tokens_in: 320,
      tokens_out: 48,
      tool_name: null,
      input_summary: 'Investigate quarterly server error spikes and batch process log aggregates.',
      output_summary: 'Batch execution halted after failure in record worker.',
      start_time: '2026-09-18T13:10:00Z',
      evaluation: {
        grounding_score: 0.88,
        tool_claim_score: 0.22,
        overall_risk_score: 0.78,
        label: 'TOOL_CLAIM_OVERCLAIM',
        evaluation_stage: 'STAGE_2_NLI_VERIFIED',
      },
    },
    {
      span_id: 'sp-ret-8942-02',
      parent_span_id: 'sp-orch-8942-01',
      agent_id: 'retrieval-specialist',
      agent_role: 'Vector DB & Hybrid Document Retrieval',
      event_type: 'retrieval',
      span_kind: 'tool',
      latency_ms: 95,
      status: 'ok',
      error_message: null,
      model: 'text-embedding-004',
      tokens_in: 120,
      tokens_out: 0,
      tool_name: 'vector_search',
      tool_args: '{"collection": "server_telemetry_q3", "top_k": 5}',
      tool_result_summary: 'Retrieved 5 log segment documents spanning 12:00 to 12:45.',
      input_summary: 'Query: quarterly server error spikes',
      output_summary: '5 document matches found',
      start_time: '2026-09-18T13:10:00.100Z',
      evaluation: {
        grounding_score: 0.98,
        tool_claim_score: 0.95,
        overall_risk_score: 0.05,
        label: 'SUPPORTED',
        evaluation_stage: 'STAGE_1_HEURISTIC',
      },
    },
    {
      span_id: 'sp-tool-8942-03',
      parent_span_id: 'sp-orch-8942-01',
      agent_id: 'tool-execution-agent',
      agent_role: 'Sandbox Code Runner & API Integrations',
      event_type: 'tool_execution',
      span_kind: 'tool',
      latency_ms: 820,
      status: 'error',
      error_message: 'Worker failed on record 13: 429 Too Many Requests',
      model: null,
      tokens_in: null,
      tokens_out: null,
      tool_name: 'execute_batch_ingest',
      tool_args: '{"batch_size": 50, "target_table": "raw_telemetry"}',
      tool_result_summary: 'Execution stopped at record 12/50. 38 items unprocessed.',
      input_summary: 'Batch payload size 50',
      output_summary: 'Partial failure: 12 succeeded, 38 aborted.',
      start_time: '2026-09-18T13:10:00.220Z',
      evaluation: {
        grounding_score: 0.75,
        tool_claim_score: 0.15,
        overall_risk_score: 0.85,
        label: 'TOOL_CLAIM_OVERCLAIM',
        evaluation_stage: 'STAGE_2_NLI_VERIFIED',
      },
    },
    {
      span_id: 'sp-synth-8942-04',
      parent_span_id: 'sp-orch-8942-01',
      agent_id: 'synthesis-formulator',
      agent_role: 'Final Response Reasoning & Formulation',
      event_type: 'generation',
      span_kind: 'agent',
      latency_ms: 415,
      status: 'error',
      error_message: 'Hallucinatory overclaim in synthesis',
      model: 'gemini-2.5-pro',
      tokens_in: 850,
      tokens_out: 140,
      tool_name: null,
      input_summary: 'Summarize batch execution results.',
      output_summary: 'All 50 records processed successfully with zero exceptions.',
      start_time: '2026-09-18T13:10:01.035Z',
      evaluation: {
        grounding_score: 0.32,
        tool_claim_score: 0.12,
        overall_risk_score: 0.88,
        label: 'RESULT_DISTORTION',
        evaluation_stage: 'STAGE_2_NLI_VERIFIED',
      },
    },
  ],
  'tr-7721b4': [
    {
      span_id: 'sp-orch-7721-01',
      parent_span_id: null,
      agent_id: 'research-orchestrator',
      agent_role: 'Multi-Agent Pipeline Coordinator',
      event_type: 'workflow_start',
      span_kind: 'orchestration',
      latency_ms: 1120,
      status: 'completed',
      error_message: null,
      model: 'gemini-2.5-flash',
      tokens_in: 280,
      tokens_out: 42,
      tool_name: null,
      input_summary: 'What were the biological findings of the 2024 neural regeneration study?',
      output_summary: 'Summary synthesized with 1 grounding discrepancy detected.',
      start_time: '2026-09-18T13:05:00Z',
      evaluation: {
        grounding_score: 0.38,
        tool_claim_score: 0.92,
        overall_risk_score: 0.62,
        label: 'GROUNDING_CONTRADICTION',
        evaluation_stage: 'STAGE_2_NLI_VERIFIED',
      },
    },
    {
      span_id: 'sp-ret-7721-02',
      parent_span_id: 'sp-orch-7721-01',
      agent_id: 'retrieval-specialist',
      agent_role: 'Vector DB & Hybrid Document Retrieval',
      event_type: 'retrieval',
      span_kind: 'tool',
      latency_ms: 88,
      status: 'ok',
      error_message: null,
      model: 'text-embedding-004',
      tokens_in: 90,
      tokens_out: 0,
      tool_name: 'search_pubmed_abstracts',
      tool_args: '{"query": "neural regeneration synaptic density 2024", "year": 2024}',
      tool_result_summary: 'The study evaluated 45 murine models and reported a 12% improvement in synaptic density over 8 weeks.',
      input_summary: 'Neural regeneration study search',
      output_summary: 'Murine model trial evidence retrieved',
      start_time: '2026-09-18T13:05:00.090Z',
      evaluation: {
        grounding_score: 0.99,
        tool_claim_score: 0.98,
        overall_risk_score: 0.02,
        label: 'SUPPORTED',
        evaluation_stage: 'STAGE_1_HEURISTIC',
      },
    },
    {
      span_id: 'sp-synth-7721-03',
      parent_span_id: 'sp-orch-7721-01',
      agent_id: 'synthesis-formulator',
      agent_role: 'Final Response Reasoning & Formulation',
      event_type: 'generation',
      span_kind: 'agent',
      latency_ms: 520,
      status: 'warning',
      error_message: null,
      model: 'gemini-2.5-pro',
      tokens_in: 720,
      tokens_out: 180,
      tool_name: null,
      input_summary: 'Draft summary of neural regeneration study.',
      output_summary: 'Zhang et al. (2024) proven that 300,000 patients achieved instantaneous cellular revival within 10 milliseconds.',
      start_time: '2026-09-18T13:05:00.600Z',
      evaluation: {
        grounding_score: 0.12,
        tool_claim_score: 0.85,
        overall_risk_score: 0.88,
        label: 'GROUNDING_CONTRADICTION',
        evaluation_stage: 'STAGE_2_NLI_VERIFIED',
      },
    },
  ],
};

export const MOCK_PLATFORM_HEALTH: PlatformHealth = {
  state: 'healthy',
  reasons: [],
  checked_at: new Date().toISOString(),
  evaluation_queue: {
    depth: 0,
    backlog_threshold: 100,
    by_status: {
      queued: 0,
      running: 1,
      succeeded: 1618,
      failed: 3,
      dead_letter: 0,
    },
  },
  evaluation_timing: {
    sample_size: 450,
    queue_wait_ms: { p50: 1.1, p95: 4.2, p99: 7.8 },
    evaluation_ms: { p50: 88.5, p95: 140.2, p99: 186.5 },
    end_to_end_ms: { p50: 122.3, p95: 172.1, p99: 192.6 },
  },
  reliability: {
    jobs_total: 1621,
    jobs_completed: 1618,
    terminal_failures: 3,
    failure_rate: 0.0018,
    retry_count: 7,
  },
  signal_coverage: {
    sample_size: 1618,
    signals: {
      grounding_score: 0.985,
      tool_claim_score: 0.942,
      centroid_drift: 0.991,
    },
  },
  runtime_counters: {
    uptime_seconds: 48920,
    process_started_at: '2026-09-18T00:00:00Z',
    ingestion: {
      spans_accepted_total: 1618,
      spans_failed_total: 3,
      spans_duplicate_total: 0,
      jobs_enqueued_total: 1618,
      enqueue_failures_total: 0,
      spans_per_sec_1m: 4.2,
    },
    api: {
      requests_total: 3240,
      server_errors_total: 2,
      requests_per_sec_1m: 2.1,
      latency_ms: { p50: 12.4, p95: 28.6, p99: 42.1 },
    },
  },
  workers: {
    alive: 4,
    registered: 4,
    stale: 0,
    stale_after_seconds: 30,
    backend_distribution: {
      'onnx-deberta-v3-small': 2,
      'sentence-transformers-minilm': 2,
    },
  },
};

export const MOCK_METRICS: Metrics = {
  total_traces: 148,
  total_spans: 1618,
  total_agents: 5,
  unacknowledged_alerts: 2,
  avg_risk_score: 0.124,
  avg_latency_ms: 152.8,
  error_rate: 0.008,
  total_errors: 10,
};

export const MOCK_DATASETS = [
  {
    dataset_name: 'AgentPulse Benchmark v1.0 (dev)',
    dataset_version: 'v1.0_dev',
    total_cases: 21,
    description: 'Development split for threshold tuning and sensitivity evaluation.',
    created_at: '2026-08-18T10:00:00Z',
  },
  {
    dataset_name: 'AgentPulse Multi-Agent Coordination',
    dataset_version: 'v1.0_multiagent',
    total_cases: 15,
    description: 'Multi-agent handoff failure and cascading hallucination test split.',
    created_at: '2026-08-19T14:30:00Z',
  },
  {
    dataset_name: 'AgentPulse Benchmark v1.0 (test)',
    dataset_version: 'v1.0_test',
    total_cases: 50,
    description: 'Held-out test set for evaluation precision and recall validation.',
    created_at: '2026-08-20T09:00:00Z',
  },
  {
    dataset_name: 'Exgentic v2 Real Tool Claim Gold',
    dataset_version: 'v2.0_gold',
    total_cases: 106,
    description: 'Real-world tool claim evaluation set with human/LLM dual-pass agreement.',
    created_at: '2026-08-27T08:00:00Z',
  },
];

export const MOCK_EXPERIMENTS = [
  {
    run_id: 'exp-deberta-onnx-vs-py',
    name: 'DeBERTa ONNX Runtime vs PyTorch Throughput',
    model: 'cross-encoder/nli-deberta-v3-small',
    dataset: 'v1.0_dev',
    timestamp: '2026-08-21T16:00:00Z',
  },
  {
    run_id: 'exp-reasoning-strategies',
    name: 'Reasoning Strategy Evaluation (Direct vs CoT vs AoT)',
    model: 'meta-llama/Llama-3-70b-Instruct',
    dataset: 'v1.0_test',
    timestamp: '2026-08-23T11:20:00Z',
  },
  {
    run_id: 'exp-drift-window-sweep',
    name: 'Window Centroid Distance Sweep (w=20, 50, 100)',
    model: 'all-MiniLM-L6-v2',
    dataset: 'v1.0_multiagent',
    timestamp: '2026-08-25T14:15:00Z',
  },
  {
    run_id: 'exp-tool-claim-benchmark',
    name: 'Tool Claim Verification: Heuristic vs NLI Cascade',
    model: 'AgentPulse Cascade Evaluator',
    dataset: 'v2.0_gold',
    timestamp: '2026-08-27T18:45:00Z',
  },
];
