"""add worker_heartbeats and retention_runs for self-monitoring

Revision ID: 1ccaf1189def
Revises: 8d86fee0d663
Create Date: 2026-08-28 00:26:16.171543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Required: SQLModel renders string columns as `sqlmodel.sql.sqltypes.AutoString()`
# in autogenerated migrations but does not emit the import for it. Without this
# line every generated migration fails at runtime with NameError on first use.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ccaf1189def'
down_revision: Union[str, Sequence[str], None] = '8d86fee0d663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cutoff', sa.DateTime(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('batches', sa.Integer(), nullable=False),
    sa.Column('total_rows_deleted', sa.Integer(), nullable=False),
    sa.Column('rows_deleted_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_runs_started_at'), ['started_at'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('jobs_processed', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('nli_backend', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('embedding_backend', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('backend_degraded', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_last_heartbeat_at'))

    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('retention_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_runs_started_at'))

    op.drop_table('retention_runs')
    # ### end Alembic commands ###
