"""add api_keys table for multi-key authentication

The backend recognised exactly one credential, read from AGENTPULSE_API_KEY and
compared directly in the middleware. Nothing could be revoked, nothing could be
attributed, and granting access to one caller meant granting everybody's.

Only a hash is stored. The plaintext is returned once at creation and never
written down, so this table leaking does not leak a working credential.
`key_prefix` is the non-secret half and is indexed, so verification finds one
row instead of scanning -- searching by hash would work but would read the whole
table on every request.

`revoked_at` is a timestamp rather than a delete, so a revoked key stays
auditable and a sudden run of 401s can be explained afterwards.

The environment key keeps working. It is now one valid credential among several
rather than the only one the system can recognise, which is what lets an
existing deployment upgrade without an outage.

Revision ID: 30ca7751ff88
Revises: c4b7e91a2f08
Create Date: 2026-09-17 02:40:09.705080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Required: SQLModel renders string columns as `sqlmodel.sql.sqltypes.AutoString()`
# in autogenerated migrations but does not emit the import for it. Without this
# line every generated migration fails at runtime with NameError on first use.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30ca7751ff88'
down_revision: Union[str, Sequence[str], None] = 'c4b7e91a2f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_owner_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
