"""baseline existing schema

Revision ID: 60a86ca23d8c
Revises: 
Create Date: 2026-08-27 18:10:13.712811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Required: SQLModel renders string columns as `sqlmodel.sql.sqltypes.AutoString()`
# in autogenerated migrations but does not emit the import for it. Without this
# line every generated migration fails at runtime with NameError on first use.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60a86ca23d8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_records',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('total_spans', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_risk_score', sa.Float(), nullable=True),
    sa.Column('current_asi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('baseline_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'baseline_type', name='uq_baseline_agent_type')
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselines_agent_id'), ['agent_id'], unique=False)

    op.create_table('dataset_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_query', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('agent_claim', sa.Text(), nullable=False),
    sa.Column('expected_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_failure_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_failure', sa.Boolean(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_cases_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_cases_dataset_name'), ['dataset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_cases_dataset_version'), ['dataset_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_cases_trace_id'), ['trace_id'], unique=False)

    op.create_table('drift_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('centroid_distance', sa.Float(), nullable=True),
    sa.Column('tool_drift', sa.Float(), nullable=True),
    sa.Column('quality_drift', sa.Float(), nullable=True),
    sa.Column('error_rate_delta', sa.Float(), nullable=True),
    sa.Column('stability_index', sa.Float(), nullable=True),
    sa.Column('baseline_size', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_records_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_records_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('mean_risk', sa.Float(), nullable=True),
    sa.Column('mean_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_runs_experiment_id'), ['experiment_id'], unique=True)

    op.create_table('traces',
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_spans', sa.Integer(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traces_pipeline_id'), ['pipeline_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)

    op.create_table('spans',
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('span_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('input_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('tool_result_summary', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ),
    sa.PrimaryKeyConstraint('span_id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spans_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_trace_id'), ['trace_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('span_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grounding_score', sa.Float(), nullable=True),
    sa.Column('contradiction_score', sa.Float(), nullable=True),
    sa.Column('tool_claim_score', sa.Float(), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('disagreement_score', sa.Float(), nullable=True),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entailment_prob', sa.Float(), nullable=True),
    sa.Column('contradiction_prob', sa.Float(), nullable=True),
    sa.Column('neutral_prob', sa.Float(), nullable=True),
    sa.Column('evaluation_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evaluator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('threshold_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluator_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['span_id'], ['spans.span_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_span_id'), ['span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_trace_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_span_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spans_trace_id'))
        batch_op.drop_index(batch_op.f('ix_spans_agent_id'))

    op.drop_table('spans')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_pipeline_id'))

    op.drop_table('traces')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_runs_experiment_id'))

    op.drop_table('experiment_runs')
    with op.batch_alter_table('drift_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_drift_records_agent_id'))

    op.drop_table('drift_records')
    with op.batch_alter_table('dataset_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_cases_trace_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_cases_dataset_version'))
        batch_op.drop_index(batch_op.f('ix_dataset_cases_dataset_name'))
        batch_op.drop_index(batch_op.f('ix_dataset_cases_case_id'))

    op.drop_table('dataset_cases')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_agent_id'))

    op.drop_table('baselines')
    op.drop_table('agent_records')
    # ### end Alembic commands ###
