"""add window_centroid_distance to drift_records

The rebuilt drift detector measures a baseline-window mean against a
current-window mean. That value is what DRIFT_DETECTED alerts fire on, but it
was never persisted -- it only ever reached operators inside the alert payload,
so it could not be queried, charted, or compared after the fact. This column
makes the signal the project validated externally (false alarms 0.0152,
detection 0.9192, AUC 0.991 on the held-out split) a first-class stored value
alongside the older spike metric, which is kept unchanged.

Nullable on purpose: the metric is undefined until both windows fill, and a
null must keep meaning "not enough samples yet" rather than "no drift".

Revision ID: c4b7e91a2f08
Revises: 1ccaf1189def
Create Date: 2026-08-30 16:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Required: SQLModel renders string columns as `sqlmodel.sql.sqltypes.AutoString()`
# in autogenerated migrations but does not emit the import for it. Without this
# line every generated migration fails at runtime with NameError on first use.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4b7e91a2f08'
down_revision: Union[str, Sequence[str], None] = '1ccaf1189def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('drift_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_centroid_distance', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('drift_records', schema=None) as batch_op:
        batch_op.drop_column('window_centroid_distance')
